# Generated by Django 5.2.8 on 2025-11-23 16:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='Mailgun message ID', max_length=255, unique=True)),
                ('sender', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.TextField(blank=True, null=True)),
                ('body_plain', models.TextField(blank=True, null=True)),
                ('body_html', models.TextField(blank=True, null=True)),
                ('raw_mime', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Raw Mailgun event JSON or headers', null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
    ]
