# Generated by Django 5.2.8 on 2025-11-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_email', '0002_emailattachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailAttachment',
        ),
    ]
